const Spaza={
 getCart(){return JSON.parse(localStorage.getItem('spazaCart')||'[]')},
 saveCart(c){localStorage.setItem('spazaCart',JSON.stringify(c));this.updateCartCount()},
 updateCartCount(){const e=document.getElementById('cartCount');if(e)e.textContent=this.getCart().reduce((n,x)=>n+Number(x.qty||0),0)},
 money(n){return 'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})},
 esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))},
 async getProducts(){if(!window.SpazaDB)return[];const {data,error}=await SpazaDB.from('products').select('id,name,description,image_url,status,created_at,categories(id,name),brands(id,name),seller_offers(id,price,status,sellers(id,business_name,rating,status),inventory(quantity,reserved_quantity))').eq('status','ACTIVE').order('created_at',{ascending:false});if(error){console.error(error);return[]}return data||[]},
 min(p){const a=(p.seller_offers||[]).filter(x=>x.status==='ACTIVE');return a.length?Math.min(...a.map(x=>Number(x.price))):null},
 card(p){const price=this.min(p);return `<article class="product-card"><a class="product-image" href="product.html?id=${encodeURIComponent(p.id)}">${p.image_url?`<img src="${this.esc(p.image_url)}" alt="${this.esc(p.name)}" style="max-width:100%;max-height:100%;object-fit:contain">`:'🛍️'}</a><div class="product-info"><small>${this.esc(p.categories?.name||'Marketplace')}</small><a class="product-name" href="product.html?id=${encodeURIComponent(p.id)}">${this.esc(p.name)}</a><p>${this.esc(p.description||'View product details and seller offers.')}</p>${price!==null?`<strong class="price">From ${this.money(price)}</strong>`:'<small>No active offer</small>'}<br><a class="button primary" href="product.html?id=${encodeURIComponent(p.id)}">View offers</a></div></article>`},
 async renderHome(){const e=document.getElementById('featuredProducts');if(!e)return;const p=(await this.getProducts()).slice(0,6);e.innerHTML=p.length?p.map(x=>this.card(x)).join(''):'<div class="empty"><h3>No products yet</h3><p>Approved sellers will add products through Seller Centre.</p></div>'},
 async renderShop(){const e=document.getElementById('shopProducts');if(!e)return;let p=await this.getProducts(),u=new URLSearchParams(location.search),q=(u.get('q')||'').toLowerCase(),cat=u.get('category')||'all';const f=document.getElementById('categoryFilter');if(f&&cat!=='all')f.value=cat;cat=f?.value||cat;if(q)p=p.filter(x=>`${x.name} ${x.description||''} ${x.categories?.name||''} ${x.brands?.name||''}`.toLowerCase().includes(q));if(cat!=='all')p=p.filter(x=>x.categories?.name===cat);const sort=document.getElementById('sortFilter')?.value||'featured';if(sort==='priceAsc')p.sort((a,b)=>(this.min(a)??Infinity)-(this.min(b)??Infinity));if(sort==='priceDesc')p.sort((a,b)=>(this.min(b)??-1)-(this.min(a)??-1));e.innerHTML=p.length?p.map(x=>this.card(x)).join(''):'<div class="empty"><h3>No products found</h3><p>Try another search or filter.</p></div>';const c=document.getElementById('resultCount');if(c)c.textContent=`${p.length} product${p.length===1?'':'s'}`},
 async renderProduct(){const e=document.getElementById('productDetails');if(!e)return;const id=new URLSearchParams(location.search).get('id');if(!id||!window.SpazaDB){e.innerHTML='<div class="empty"><h2>Product not found</h2><a class="button primary" href="shop.html">Back to shop</a></div>';return}
 const {data:p,error}=await SpazaDB.from('products').select('id,name,description,image_url,status,created_at,categories(id,name),brands(id,name),seller_offers(id,price,condition,delivery_information,return_policy,status,sellers(id,business_name,rating,status),inventory(quantity,reserved_quantity))').eq('id',id).eq('status','ACTIVE').single();
 if(error||!p){e.innerHTML='<div class="empty"><h2>Product not found</h2><p>This product is unavailable or has not been published.</p><a class="button primary" href="shop.html">Back to shop</a></div>';return}
 const offers=(p.seller_offers||[]).filter(x=>x.status==='ACTIVE').sort((a,b)=>Number(a.price)-Number(b.price));
 const available=x=>Math.max(0,Number(x.inventory?.quantity||0)-Number(x.inventory?.reserved_quantity||0));
 const delivery=x=>{const d=x.delivery_information;if(!d)return'Contact seller for delivery options';if(typeof d==='string')return d;return Object.entries(d).map(([k,v])=>`${this.esc(k)}: ${this.esc(typeof v==='object'?JSON.stringify(v):v)}`).join(' • ')};
 e.innerHTML=`<section class="product-main"><div class="big-product-image">${p.image_url?`<img src="${this.esc(p.image_url)}" alt="${this.esc(p.name)}" style="max-width:100%;max-height:100%;object-fit:contain">`:'🛍️'}</div><div class="product-summary"><small>${this.esc(p.categories?.name||'Marketplace')}${p.brands?.name?' · '+this.esc(p.brands.name):''}</small><h1>${this.esc(p.name)}</h1><p class="description">${this.esc(p.description||'Product details supplied by the seller.')}</p><div class="offer-box"><div><small>Best active offer</small><strong>${offers.length?this.money(offers[0].price):'—'}</strong><span>${offers.length?offers.length+' seller offer'+(offers.length===1?'':'s'): 'No active offers'}</span></div>${offers.length&&available(offers[0])>0?`<button class="button primary" onclick="Spaza.addOffer('${offers[0].id}')">Add to cart</button>`:''}</div></div></section>
 <section class="seller-section"><div class="section-title"><div><p class="eyebrow">COMPARE OFFERS</p><h2>Choose your seller</h2><p class="page-intro">Compare price, stock, seller rating, delivery and returns.</p></div><span>${offers.length} active offer${offers.length===1?'':'s'}</span></div><div class="seller-list">${offers.length?offers.map((x,i)=>`<article class="seller-offer ${i===0?'best-offer':''}"><div><strong>${this.esc(x.sellers?.business_name||'Seller')}</strong><div>Seller rating: ${x.sellers?.rating!=null?Number(x.sellers.rating).toFixed(1):'Not rated'}</div><small>${available(x)} available</small></div><div class="offer-details"><strong class="offer-price">${this.money(x.price)}</strong><small>${this.esc(x.condition||'Condition not specified')}</small><small>Delivery: ${delivery(x)}</small><small>Returns: ${x.return_policy?this.esc(typeof x.return_policy==='object'?JSON.stringify(x.return_policy):x.return_policy):'Seller policy applies'}</small></div><button class="button primary" ${available(x)<=0?'disabled':''} onclick="Spaza.addOffer('${x.id}')">${available(x)>0?'Buy from seller':'Out of stock'}</button></article>`).join(''):'<div class="empty"><h3>No active seller offers</h3><p>Approved sellers have not published an offer for this product.</p></div>'}</div></section>
 <section class="product-info-tabs"><div class="tab-panel"><h3>Overview</h3><p>${this.esc(p.description||'No additional overview has been supplied.')}</p></div><div class="tab-panel"><h3>Specifications</h3><p>Specifications will appear here when supplied by the seller.</p></div><div class="tab-panel"><h3>Reviews</h3><p>Customer reviews will appear here after verified purchases and approved reviews.</p></div><div class="tab-panel"><h3>Questions</h3><p>Product questions and seller answers will appear here.</p></div></section>`},
 async addOffer(id){const {data:o,error}=await SpazaDB.from('seller_offers').select('id,product_id,price,status,sellers(business_name),products(name)').eq('id',id).eq('status','ACTIVE').single();if(error||!o){alert('Offer is no longer available.');return}const c=this.getCart(),f=c.find(x=>x.key===id);if(f)f.qty++;else c.push({key:id,offerId:id,productId:o.product_id,name:o.products?.name||'Product',seller:o.sellers?.business_name||'Seller',price:Number(o.price),qty:1});this.saveCart(c);alert('Added to cart.')},
 renderCart(){const e=document.getElementById('cartItems');if(!e)return;const c=this.getCart();if(!c.length){e.innerHTML='<div class="empty"><h2>Your cart is empty</h2><a class="button primary" href="shop.html">Start shopping</a></div>';return}const t=c.reduce((s,x)=>s+x.price*x.qty,0);e.innerHTML=`<div class="cart-layout"><div>${c.map((x,i)=>`<div class="cart-item"><div class="cart-icon">🛍️</div><div><strong>${this.esc(x.name)}</strong><small>Seller: ${this.esc(x.seller)}</small><div>${this.money(x.price)} × ${x.qty}</div></div><button onclick="Spaza.removeCart(${i})">Remove</button></div>`).join('')}</div><aside class="summary"><h3>Order summary</h3><div><span>Subtotal</span><strong>${this.money(t)}</strong></div><div><span>Delivery</span><span>At checkout</span></div><hr><div><strong>Total</strong><strong>${this.money(t)}</strong></div><a class="button primary full" href="checkout.html">Proceed to checkout</a></aside></div>`},
 removeCart(i){const c=this.getCart();c.splice(i,1);this.saveCart(c);this.renderCart()},
 menu(){const b=document.getElementById('menuButton')||document.getElementById('menuBtn'),d=document.getElementById('drawer'),o=document.getElementById('overlay'),c=document.getElementById('closeDrawer')||document.getElementById('closeMenu');if(!b||!d)return;const close=()=>{d.classList.remove('open');o?.classList.remove('show')};b.onclick=()=>{d.classList.add('open');o?.classList.add('show')};c?.addEventListener('click',close);o?.addEventListener('click',close)},
 search(){const b=document.getElementById('searchBtn');if(b)b.onclick=()=>{const q=document.getElementById('searchInput')?.value.trim()||'';location.href=`shop.html${q?'?q='+encodeURIComponent(q):''}`}},
 async init(){this.updateCartCount();this.menu();this.search();await this.renderHome();await this.renderShop();await this.renderProduct();this.renderCart()}
};window.Spaza=Spaza;window.SpazaApp=Spaza;document.addEventListener('DOMContentLoaded',()=>Spaza.init());
